import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="w-fill flex items-center justify-between border-b-2 p-4 text-xl font-bold">
      <div>Gallery</div>
      <div>Sign in</div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`flex-column flex w-full gap-4 ${GeistSans.variable}`}
    >
      <body className="w-full">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
